/**
 * Copyright IBM Corp. 2018, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

const fs = require('fs-extra');
const path = require('path');

const BANNER = `/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */`;

/**
 * Process icons in chunks to limit concurrent I/O and memory usage.
 * @param {Array} items
 * @param {number} chunkSize
 * @param {Function} fn
 */
async function processInChunks(items, chunkSize, fn) {
  for (let i = 0; i < items.length; i += chunkSize) {
    const chunk = items.slice(i, i + chunkSize);
    await Promise.all(chunk.map(fn));
  }
}

async function builder(metadata, { output }) {
  const modules = metadata.icons.flatMap((icon) => {
    return icon.output.map((size) => {
      return {
        descriptor: size.descriptor,
        filepath: size.filepath,
        moduleName: size.moduleName,
      };
    });
  });

  const esDir = path.join(output, 'es');
  const libDir = path.join(output, 'lib');

  // Write individual icon modules directly to disk — no bundler needed.
  // Each module is a single default export of a JSON descriptor object,
  // which requires no transformation beyond serialization.
  const CHUNK_SIZE = 200;
  await processInChunks(modules, CHUNK_SIZE, async (m) => {
    const json = JSON.stringify(m.descriptor);

    const esFile = path.join(esDir, m.filepath);
    const libFile = path.join(libDir, m.filepath);

    await Promise.all([
      fs
        .ensureFile(esFile)
        .then(() =>
          fs.writeFile(esFile, `${BANNER}\nexport default ${json};\n`, 'utf8')
        ),
      fs
        .ensureFile(libFile)
        .then(() =>
          fs.writeFile(
            libFile,
            `${BANNER}\n'use strict';\n\nmodule.exports = ${json};\n`,
            'utf8'
          )
        ),
    ]);
  });

  // Generate barrel index.js files via string concatenation
  let esIndex = `${BANNER}\n`;
  let libRequires = '';
  let libExports = '';

  for (const m of modules) {
    esIndex += `\nexport { default as ${m.moduleName} } from './${m.filepath}';`;

    // Generate a safe variable name from the filepath for CJS
    const varName = filepathToVarName(m.filepath);
    libRequires += `var ${varName} = require('./${m.filepath}');\n`;
    libExports += `exports.${m.moduleName} = ${varName};\n`;
  }

  const libIndex = `${BANNER}\n'use strict';\n\n${libRequires}\n${libExports}`;

  await Promise.all([
    fs.writeFile(path.join(esDir, 'index.js'), esIndex + '\n', 'utf8'),
    fs.writeFile(path.join(libDir, 'index.js'), libIndex, 'utf8'),
  ]);

  // Generate UMD bundle directly as a string — no Rollup needed.
  // The UMD format inlines all icon descriptors into a single IIFE.
  await generateUmdBundle(modules, path.join(output, 'umd/index.js'));
}

/**
 * Generate a UMD bundle by directly writing the wrapper + inlined descriptors.
 * This avoids loading all modules into a Rollup module graph.
 */
async function generateUmdBundle(modules, outputPath) {
  const chunks = [];

  chunks.push(
    `(function (global, factory) {`,
    `\ttypeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :`,
    `\ttypeof define === 'function' && define.amd ? define(['exports'], factory) :`,
    `\t(global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.CarbonIcons = {}));`,
    `})(this, (function (exports) { 'use strict';`,
    ``
  );

  // Inline each icon descriptor as a variable and export it
  for (let i = 0; i < modules.length; i++) {
    const m = modules[i];
    const varName = `_icon${i}`;
    chunks.push(`\tvar ${varName} = ${JSON.stringify(m.descriptor)};`);
  }

  chunks.push('');

  for (let i = 0; i < modules.length; i++) {
    const m = modules[i];
    const varName = `_icon${i}`;
    const exportName = /^[a-zA-Z_$]/.test(m.moduleName)
      ? m.moduleName
      : `_${m.moduleName}`;
    chunks.push(`\texports.${exportName} = ${varName};`);
  }

  chunks.push('', `}));`, '');

  await fs.ensureFile(outputPath);
  await fs.writeFile(outputPath, chunks.join('\n'), 'utf8');
}

/**
 * Convert a filepath like 'watson-health/3D-Cursor/32.js' into a safe JS
 * variable name: replace non-alphanumeric chars with underscores, prefix
 * with _ if it starts with a digit.
 */
function filepathToVarName(filepath) {
  let name = filepath.replace(/[^a-zA-Z0-9]/g, '_');
  if (/^[0-9]/.test(name)) {
    name = '_' + name;
  }
  return name;
}

module.exports = builder;
