/**
 * Copyright IBM Corp. 2018, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

const fs = require('fs-extra');
const path = require('path');
const { rollup } = require('rollup');
const virtual = require('./plugins/virtual');

const BANNER = `/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */`;

/**
 * Process icons in chunks to limit concurrent I/O and memory usage.
 * @param {Array} items
 * @param {number} chunkSize
 * @param {Function} fn
 */
async function processInChunks(items, chunkSize, fn) {
  for (let i = 0; i < items.length; i += chunkSize) {
    const chunk = items.slice(i, i + chunkSize);
    await Promise.all(chunk.map(fn));
  }
}

async function builder(metadata, { output }) {
  const modules = metadata.icons.flatMap((icon) => {
    return icon.output.map((size) => {
      return {
        descriptor: size.descriptor,
        filepath: size.filepath,
        moduleName: size.moduleName,
      };
    });
  });

  const esDir = path.join(output, 'es');
  const libDir = path.join(output, 'lib');

  // Write individual icon modules directly to disk — no bundler needed.
  // Each module is a single default export of a JSON descriptor object,
  // which requires no transformation beyond serialization.
  const CHUNK_SIZE = 200;
  await processInChunks(modules, CHUNK_SIZE, async (m) => {
    const json = JSON.stringify(m.descriptor);

    const esFile = path.join(esDir, m.filepath);
    const libFile = path.join(libDir, m.filepath);

    await Promise.all([
      fs
        .ensureFile(esFile)
        .then(() =>
          fs.writeFile(esFile, `${BANNER}\nexport default ${json};\n`, 'utf8')
        ),
      fs
        .ensureFile(libFile)
        .then(() =>
          fs.writeFile(
            libFile,
            `${BANNER}\n'use strict';\n\nmodule.exports = ${json};\n`,
            'utf8'
          )
        ),
    ]);
  });

  // Generate barrel index.js files via string concatenation
  let esIndex = `${BANNER}\n`;
  let libRequires = '';
  let libExports = '';

  for (const m of modules) {
    esIndex += `\nexport { default as ${m.moduleName} } from './${m.filepath}';`;

    // Generate a safe variable name from the filepath for CJS
    const varName = filepathToVarName(m.filepath);
    libRequires += `var ${varName} = require('./${m.filepath}');\n`;
    libExports += `exports.${m.moduleName} = ${varName};\n`;
  }

  const libIndex = `${BANNER}\n'use strict';\n\n${libRequires}\n${libExports}`;

  await Promise.all([
    fs.writeFile(path.join(esDir, 'index.js'), esIndex + '\n', 'utf8'),
    fs.writeFile(path.join(libDir, 'index.js'), libIndex, 'utf8'),
  ]);

  // UMD: still use Rollup since it needs to inline all modules into one file.
  // Feed it only the index entry — Rollup resolves the re-exports from the
  // already-written ES files on disk.
  const umdIndex = esIndex;
  const umdFiles = { 'index.js': umdIndex };

  for (const m of modules) {
    umdFiles[m.filepath] = `export default ${JSON.stringify(m.descriptor)};`;
  }

  const umd = await rollup({
    input: 'index.js',
    plugins: [virtual(umdFiles)],
  });

  await umd.write({
    file: path.join(output, 'umd/index.js'),
    format: 'umd',
    name: 'CarbonIcons',
  });

  await umd.close();
}

/**
 * Convert a filepath like 'watson-health/3D-Cursor/32.js' into a safe JS
 * variable name that matches Rollup's convention: replace non-alphanumeric
 * chars with underscores, prefix with _ if it starts with a digit.
 */
function filepathToVarName(filepath) {
  let name = filepath.replace(/[^a-zA-Z0-9]/g, '_');
  if (/^[0-9]/.test(name)) {
    name = '_' + name;
  }
  return name;
}

module.exports = builder;
