/**
 * Copyright IBM Corp. 2018, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

const fs = require('fs-extra');
const path = require('path');
const { rollup } = require('rollup');
const virtual = require('../plugins/virtual');

const BANNER = `/**
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */`;
const external = ['@carbon/icon-helpers', 'vue'];

/**
 * Process items in chunks to limit concurrent I/O and memory usage.
 */
async function processInChunks(items, chunkSize, fn) {
  for (let i = 0; i < items.length; i += chunkSize) {
    const chunk = items.slice(i, i + chunkSize);
    await Promise.all(chunk.map(fn));
  }
}

async function builder(metadata, { output }) {
  const modules = metadata.icons.flatMap((icon) => {
    return icon.output.map((size) => {
      return {
        descriptor: size.descriptor,
        filepath: size.filepath,
        moduleName: size.moduleName,
      };
    });
  });

  const esDir = path.join(output, 'es');
  const libDir = path.join(output, 'lib');

  // Write the shared utils module to both output dirs
  const utilsSrc = await fs.readFile(
    path.resolve(__dirname, './utils.js'),
    'utf8'
  );

  await fs.ensureDir(esDir);
  await fs.ensureDir(libDir);

  // ESM utils — source is already ESM
  await fs.writeFile(
    path.join(esDir, 'utils.js'),
    `${BANNER}\n${utilsSrc}`,
    'utf8'
  );

  // CJS utils — convert ESM imports/exports to CJS
  const cjsUtils = convertUtilsToCjs(utilsSrc);
  await fs.writeFile(
    path.join(libDir, 'utils.js'),
    `${BANNER}\n${cjsUtils}`,
    'utf8'
  );

  // Write individual icon modules directly to disk
  const CHUNK_SIZE = 200;
  await processInChunks(modules, CHUNK_SIZE, async (m) => {
    const attrs = JSON.stringify(m.descriptor.attrs);
    const content = JSON.stringify(m.descriptor.content);

    const esFile = path.join(esDir, m.filepath);
    const libFile = path.join(libDir, m.filepath);

    // Calculate relative path from icon file to utils.js
    const depth = m.filepath.split('/').length - 1;
    const utilsRel =
      depth > 0 ? '../'.repeat(depth) + 'utils.js' : './utils.js';

    const esSource = [
      BANNER,
      `import createSVGComponent from '${utilsRel}';`,
      '',
      `const ${m.moduleName} = createSVGComponent('${m.moduleName}', ${attrs}, ${content});`,
      '',
      `export default ${m.moduleName};`,
      '',
    ].join('\n');

    const libSource = [
      BANNER,
      `'use strict';`,
      '',
      `var createSVGComponent = require('${utilsRel}');`,
      '',
      `const ${m.moduleName} = createSVGComponent('${m.moduleName}', ${attrs}, ${content});`,
      '',
      `module.exports = ${m.moduleName};`,
      '',
    ].join('\n');

    await Promise.all([
      fs.ensureFile(esFile).then(() => fs.writeFile(esFile, esSource, 'utf8')),
      fs
        .ensureFile(libFile)
        .then(() => fs.writeFile(libFile, libSource, 'utf8')),
    ]);
  });

  // Generate barrel index.js files
  let esIndex = `${BANNER}\n\n`;
  esIndex += `export const CarbonIconsVue = {\n`;
  esIndex += `  install(Vue, options) {\n`;
  esIndex += `    const { components } = options;\n`;
  esIndex += `    Object.keys(components).forEach(key => {\n`;
  esIndex += `      Vue.component(key, components[key]);\n`;
  esIndex += `    });\n`;
  esIndex += `  },\n`;
  esIndex += `};\n`;

  let libRequires = '';
  let libExports = '';

  libExports += `exports.CarbonIconsVue = {\n`;
  libExports += `  install(Vue, options) {\n`;
  libExports += `    const { components } = options;\n`;
  libExports += `    Object.keys(components).forEach(key => {\n`;
  libExports += `      Vue.component(key, components[key]);\n`;
  libExports += `    });\n`;
  libExports += `  },\n`;
  libExports += `};\n`;

  for (const m of modules) {
    esIndex += `export { default as ${m.moduleName} } from './${m.filepath}';\n`;

    const varName = filepathToVarName(m.filepath);
    libRequires += `var ${varName} = require('./${m.filepath}');\n`;
    libExports += `exports.${m.moduleName} = ${varName};\n`;
  }

  const libIndex = `${BANNER}\n'use strict';\n\n${libRequires}\n${libExports}`;

  await Promise.all([
    fs.writeFile(path.join(esDir, 'index.js'), esIndex, 'utf8'),
    fs.writeFile(path.join(libDir, 'index.js'), libIndex, 'utf8'),
  ]);

  // UMD: still use Rollup since it needs to inline everything into one file
  const umdFiles = { 'index.js': esIndex };
  umdFiles['./utils.js'] = utilsSrc;
  for (const m of modules) {
    const attrs = JSON.stringify(m.descriptor.attrs);
    const content = JSON.stringify(m.descriptor.content);
    umdFiles[m.filepath] = [
      `import createSVGComponent from './utils.js';`,
      `const ${m.moduleName} = createSVGComponent('${m.moduleName}', ${attrs}, ${content});`,
      `export default ${m.moduleName};`,
    ].join('\n');
  }

  const umd = await rollup({
    input: 'index.js',
    external,
    plugins: [virtual(umdFiles)],
  });

  await umd.write({
    file: path.join(output, 'umd/index.js'),
    format: 'umd',
    name: 'CarbonIconsVue',
    globals: {
      '@carbon/icon-helpers': 'CarbonIconHelpers',
      vue: 'Vue',
    },
  });

  await umd.close();
}

/**
 * Convert the ESM utils source to CommonJS.
 */
function convertUtilsToCjs(source) {
  let cjs = source
    .replace(
      /import \{ getAttributes \} from '@carbon\/icon-helpers';/,
      "const { getAttributes } = require('@carbon/icon-helpers');"
    )
    .replace(/import \* as Vue from 'vue';/, "const Vue = require('vue');")
    .replace(
      /export default createSVGComponent;/,
      'module.exports = createSVGComponent;'
    );
  return `'use strict';\n\n${cjs}`;
}

/**
 * Convert a filepath into a safe JS variable name.
 */
function filepathToVarName(filepath) {
  let name = filepath.replace(/[^a-zA-Z0-9]/g, '_');
  if (/^[0-9]/.test(name)) {
    name = '_' + name;
  }
  return name;
}

module.exports = builder;
