/**
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

const babel = require('@babel/core');
const { camelCase } = require('change-case-all');
const fs = require('fs-extra');
const path = require('path');

const BANNER = `/**
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */`;

const babelPlugins = [
  '@babel/plugin-transform-react-constant-elements',
  'babel-plugin-dev-expression',
];

/**
 * Process items in chunks to limit concurrent I/O and memory usage.
 */
async function processInChunks(items, chunkSize, fn) {
  for (let i = 0; i < items.length; i += chunkSize) {
    const chunk = items.slice(i, i + chunkSize);
    await Promise.all(chunk.map(fn));
  }
}

async function builder(metadata, { output }) {
  const modules = metadata.icons.flatMap((icon) => {
    return icon.output.map((size) => {
      return {
        source: createIconFlatExport(
          size.moduleName,
          size.descriptor,
          icon.deprecated
        ),
        entrypoint: createIconEntrypoint(
          size.moduleName,
          size.descriptor,
          icon.deprecated
        ),
        filepath: size.filepath,
        moduleName: size.moduleName,
      };
    });
  });

  const BUCKET_SIZE = 250;
  const buckets = [];
  for (let i = 0; i < modules.length; i += BUCKET_SIZE) {
    buckets.push(modules.slice(i, i + BUCKET_SIZE));
  }

  const esDir = path.join(output, 'es');
  const libDir = path.join(output, 'lib');
  await fs.ensureDir(esDir);
  await fs.ensureDir(libDir);

  // Compile Icon.tsx once with Babel
  const iconTsxSource = await fs.readFile(
    path.resolve(__dirname, './components/Icon.tsx'),
    'utf8'
  );

  const iconEs = babel.transformSync(iconTsxSource, {
    babelrc: false,
    filename: 'Icon.tsx',
    presets: [
      ['@babel/preset-env', { modules: false }],
      '@babel/preset-react',
      '@babel/preset-typescript',
    ],
    plugins: babelPlugins,
  });

  const iconCjs = babel.transformSync(iconTsxSource, {
    babelrc: false,
    filename: 'Icon.tsx',
    presets: [
      '@babel/preset-env',
      '@babel/preset-react',
      '@babel/preset-typescript',
    ],
    plugins: babelPlugins,
  });

  await Promise.all([
    fs.writeFile(
      path.join(esDir, 'Icon.js'),
      `${BANNER}\n${iconEs.code}\n`,
      'utf8'
    ),
    fs.writeFile(
      path.join(libDir, 'Icon.js'),
      `${BANNER}\n${iconCjs.code}\n`,
      'utf8'
    ),
  ]);

  // Write individual icon entry point files directly to disk
  const CHUNK_SIZE = 200;
  await processInChunks(modules, CHUNK_SIZE, async (m) => {
    const esSource = compileJsx(m.entrypoint, 'esm');
    const cjsSource = compileJsx(m.entrypoint, 'cjs');

    const esFile = path.join(esDir, m.filepath);
    const libFile = path.join(libDir, m.filepath);

    await Promise.all([
      fs.ensureFile(esFile).then(() => fs.writeFile(esFile, esSource, 'utf8')),
      fs
        .ensureFile(libFile)
        .then(() => fs.writeFile(libFile, cjsSource, 'utf8')),
    ]);
  });

  // Write bucket files directly to disk
  await fs.ensureDir(path.join(esDir, '__generated__'));
  await fs.ensureDir(path.join(libDir, '__generated__'));

  for (let i = 0; i < buckets.length; i++) {
    const bucket = buckets[i];
    const filename = `__generated__/bucket-${i}.js`;

    let bucketSource = `${BANNER}

import React from 'react';
import Icon from './Icon.tsx';

const didWarnAboutDeprecation = {};`;

    for (const m of bucket) {
      bucketSource += `export ${m.source}`;
    }

    const esBucket = compileJsx(bucketSource, 'esm');
    const cjsBucket = compileJsx(bucketSource, 'cjs');

    await Promise.all([
      fs.writeFile(path.join(esDir, filename), esBucket, 'utf8'),
      fs.writeFile(path.join(libDir, filename), cjsBucket, 'utf8'),
    ]);
  }

  // Write barrel index.js
  const esIndex = [
    BANNER,
    '',
    `export { default as Icon } from './Icon.js';`,
    ...buckets.map((_, i) => `export * from './__generated__/bucket-${i}.js';`),
    '',
  ].join('\n');

  const libIndex = [
    BANNER,
    `'use strict';`,
    '',
    `var Icon_js = require('./Icon.js');`,
    ...buckets.map(
      (_, i) => `var bucket_${i} = require('./__generated__/bucket-${i}.js');`
    ),
    '',
    `exports.Icon = Icon_js;`,
    ...buckets.map(
      (_, i) =>
        `Object.keys(bucket_${i}).forEach(function (k) { if (k !== 'default' && !Object.prototype.hasOwnProperty.call(exports, k)) exports[k] = bucket_${i}[k]; });`
    ),
    '',
  ].join('\n');

  await Promise.all([
    fs.writeFile(path.join(esDir, 'index.js'), esIndex, 'utf8'),
    fs.writeFile(path.join(libDir, 'index.js'), libIndex, 'utf8'),
  ]);
}

/**
 * Compile a JSX source string to JS using Babel.
 * Resolves Icon.tsx import to ./Icon.js in the output.
 */
function compileJsx(source, format) {
  const adjusted = source.replace(
    /from ['"]\.\/Icon\.tsx['"]/g,
    "from './Icon.js'"
  );

  const result = babel.transformSync(adjusted, {
    babelrc: false,
    filename: 'component.jsx',
    presets: [
      format === 'esm'
        ? ['@babel/preset-env', { modules: false }]
        : '@babel/preset-env',
      '@babel/preset-react',
    ],
    plugins: babelPlugins,
  });

  return `${result.code}\n`;
}

/**
 * Convert the given node to a JSX string source
 * @param {object} node
 * @returns {string}
 */
function convertToJSX(node) {
  const { elem, attrs } = node;
  return `<${elem} ${formatAttributes(attrs)} />`;
}

const attributeDenylist = ['data', 'aria'];

/**
 * Determine if the given attribute should be transformed when being converted
 * to a React prop or if we should pass it through as-is
 * @param {string} attribute
 * @returns {boolean}
 */
function shouldTransformAttribute(attribute) {
  return attributeDenylist.every((prefix) => !attribute.startsWith(prefix));
}

/**
 * Serialize a given object of key, value pairs to an JSX-compatible string
 * @param {object} attrs
 * @returns {string}
 */
function formatAttributes(attrs) {
  return Object.keys(attrs).reduce((acc, key, index) => {
    const attribute = shouldTransformAttribute(key)
      ? `${camelCase(key)}="${attrs[key]}"`
      : `${key}="${attrs[key]}"`;

    if (index === 0) {
      return attribute;
    }
    return acc + ' ' + attribute;
  }, '');
}

function createIconFlatExport(moduleName, descriptor, isDeprecated = false) {
  const deprecatedBlock = isDeprecated
    ? `
    if (process.env.NODE_ENV !== "production") {
      if (!didWarnAboutDeprecation['${moduleName}']) {
        didWarnAboutDeprecation['${moduleName}'] = true;
        console.warn(
          \`The ${moduleName} component has been deprecated and will be \` +
          \`removed in the next major version of @carbon/icons-react.\`
        );
      }
    }
    `
    : '';
  return createIconSource(moduleName, descriptor, deprecatedBlock);
}

function createIconEntrypoint(moduleName, descriptor, isDeprecated = false) {
  const deprecatedPreamble = isDeprecated
    ? 'let didWarnAboutDeprecation = false;'
    : '';
  const deprecatedBlock = isDeprecated
    ? `
    if (process.env.NODE_ENV !== "production") {
      if (!didWarnAboutDeprecation) {
        didWarnAboutDeprecation = true;
        console.warn(
          \`The ${moduleName} component has been deprecated and will be \` +
          \`removed in the next major version of @carbon/icons-react.\`
        );
      }
    }
    `
    : '';
  const source = createIconSource(moduleName, descriptor, deprecatedBlock);
  return `${BANNER}
import React from 'react';
import Icon from './Icon.tsx';
${deprecatedPreamble}
${source}
export default ${moduleName};
`;
}

/**
 * Generate an icon component, which in our case is the string representation
 * of the component, from a given moduleName and icon descriptor.
 * @param {string} moduleName
 * @param {object} descriptor
 * @param {string} customBlock
 */
function createIconSource(moduleName, descriptor, customBlock = '') {
  const { attrs, content } = descriptor;
  const { width, height, viewBox, ...rest } = attrs;
  return `
    const ${moduleName} = /*#__PURE__*/ React.forwardRef(
      function ${moduleName}({ children, ...rest }, ref) {
        ${customBlock}
        return (
          <Icon
            width={${width}}
            height={${height}}
            viewBox="${viewBox}"
            ${formatAttributes(rest)}
            ref={ref}
            {...rest}>
            ${content.map(convertToJSX).join('\n')}
            {children}
          </Icon>
        );
      }
    );
  `;
}

module.exports = builder;
